script:
    - pwd
    - find $TRAVIS_BUILD_DIR -type f -path "*/soccer-embedded/Robot*.mk" -exec sed 's/.*soccer-embedded/TRAVIS_BUILD_DIR/gep' {} \;
    - cd $TRAVIS_BUILD_DIR/Robot_F4/Debug
    - cd hardware
    - cat subdir.mk
    - cd ../
    - make clean
    - make
    - cd $TRAVIS_BUILD_DIR/Robot_F7/Debug
    - make clean
    - make