# language: python
# python:
#     - "2.7"

# # Cache PlatformIO packages using Travis CI container-based infrastructure
# sudo: false
# cache:
#     directories:
#         - "~/.platformio"

# env:
    # - PLATFORMIO_PROJECT_DIR=Robot_F4
    # - PLATFORMIO_PROJECT_DIR=Robot_F7

# install:
#     - pip install -U platformio

script:
    # - platformio run -d $PLATFORMIO_PROJECT_DIR
    - pwd
    # - find $TRAVIS_BUILD_DIR -type f -exec sed -i 's/^(.*?)soccer-embedded/\$TRAVIS_BUILD_DIR/g' {} \;
    # - find $TRAVIS_BUILD_DIR -path '*/soccer-embedded/Robot*.mk' -type f -exec sed -i 's/^(.*?)soccer-embedded/\$TRAVIS_BUILD_DIR/g' {} \;
    - find $TRAVIS_BUILD_DIR -path '*/soccer-embedded/Robot*.mk' -type f -exec dirname {} \;
    - cd $TRAVIS_BUILD_DIR/Robot_F4/Debug
    - cd hardware
    - cat subdir.mk
    - cd ../
    - make clean
    - make
    - cd $TRAVIS_BUILD_DIR/Robot_F7/Debug
    - make clean
    - make