script:
    - pwd
    - find $TRAVIS_BUILD_DIR -type f -path "*/soccer-embedded/Robot*.mk" -exec perl -pi.bak -e 's/(C|D):[A-Za-z:]*.*?soccer-embedded/\$TRAVIS_BUILD_DIR/g' {} \;
    - cd $TRAVIS_BUILD_DIR/Robot_F4/Debug
    - cd hardware
    - cat subdir.mk
    - cd ../
    - ls
    - make clean
    - make
    - cd $TRAVIS_BUILD_DIR/Robot_F7/Debug
    - ls
    - make clean
    - make makefile